namespace Maigret.Net.Reports.Writers;

/// <summary>Markdown report writer mirroring <c>generate_markdown_report</c>.</summary>
public sealed class MarkdownReportWriter : IReportWriter
{
    public string FormatId => "markdown";
    public string FileExtension => "md";

    public Task WriteAsync(TextWriter writer, ReportContext context, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(context);

        var found = context.Claimed.ToList();
        var idLabel = string.IsNullOrEmpty(context.IdType) ? "username" : context.IdType;

        writer.WriteLine($"# Report by searching on {idLabel} \"{context.Username}\"");
        writer.WriteLine();
        writer.WriteLine($"Generated at {context.GeneratedAtIso8601} by [Maigret.Net](https://github.com/totpero/Maigret.Net) ({context.TotalChecked} sites checked).");
        writer.WriteLine();

        writer.WriteLine("## Summary");
        writer.WriteLine();
        writer.WriteLine($"Search by {idLabel} `{context.Username}` returned **{found.Count}** account(s).");
        writer.WriteLine();

        var tagCounts = new SortedDictionary<string, int>(StringComparer.Ordinal);
        var countryCounts = new SortedDictionary<string, int>(StringComparer.Ordinal);
        foreach (var r in found)
        {
            foreach (var t in r.Tags)
            {
                if (TagUtils.IsCountryTag(t))
                {
                    var key = t.ToLowerInvariant();
                    if (key == "global")
                    {
                        continue;
                    }

                    countryCounts[key] = countryCounts.GetValueOrDefault(key) + 1;
                }
                else
                {
                    tagCounts[t] = tagCounts.GetValueOrDefault(t) + 1;
                }
            }
        }

        if (countryCounts.Count > 0)
        {
            writer.WriteLine("**Country tags:** " +
                string.Join(", ", countryCounts.OrderByDescending(p => p.Value).Select(p => $"{p.Key} (x{p.Value})")));
            writer.WriteLine();
        }
        if (tagCounts.Count > 0)
        {
            writer.WriteLine("**Website tags:** " +
                string.Join(", ", tagCounts.OrderByDescending(p => p.Value).Select(p => $"{p.Key} (x{p.Value})")));
            writer.WriteLine();
        }

        writer.WriteLine("## Accounts found");
        writer.WriteLine();
        if (found.Count == 0)
        {
            writer.WriteLine("_No claimed accounts._");
            writer.WriteLine();
        }
        else
        {
            foreach (var r in found.OrderBy(r => r.SiteName, StringComparer.Ordinal))
            {
                writer.WriteLine($"### {r.SiteName}");
                writer.WriteLine();
                writer.WriteLine($"- **URL:** [{r.SiteUrlUser}]({r.SiteUrlUser})");
                if (r.Tags.Count > 0)
                {
                    writer.WriteLine($"- **Tags:** {string.Join(", ", r.Tags)}");
                }

                if (r.IdsData is { Count: > 0 })
                {
                    foreach (var (k, v) in r.IdsData)
                    {
                        if (k.Equals("image", StringComparison.OrdinalIgnoreCase))
                        {
                            continue;
                        }

                        writer.WriteLine($"- {k}: {v}");
                    }
                }
                writer.WriteLine();
            }
        }

        writer.WriteLine("## Possible false positives");
        writer.WriteLine();
        writer.WriteLine($"This report was generated by searching for accounts matching `{context.Username}`. " +
            "Listed accounts may belong to different people who happen to share the username. " +
            "Verify findings before drawing conclusions.");
        writer.WriteLine();

        writer.WriteLine("## Ethical use");
        writer.WriteLine();
        writer.WriteLine("This report is the result of a technical collection of publicly available information. " +
            "Ensure your use complies with applicable laws (GDPR, CCPA, etc.) before further processing.");
        return Task.CompletedTask;
    }
}
