namespace Maigret.Net.Core.Errors;

/// <summary>
/// Common HTML error fingerprints, lookup tables, and threshold helpers.
/// Mirrors module-level state from <c>maigret/errors.py</c>.
/// </summary>
public static class CommonErrors
{
    /// <summary>
    /// Maps a string fingerprint that may be present in an HTML response to the
    /// <see cref="CheckError"/> it indicates.
    /// </summary>
    public static IReadOnlyDictionary<string, CheckError> Fingerprints { get; } =
        new Dictionary<string, CheckError>
        {
            ["<title>Attention Required! | Cloudflare</title>"] = new("Captcha", "Cloudflare"),
            ["<title>Just a moment</title>"] = new("Bot protection", "Cloudflare challenge page"),
            ["Please stand by, while we are checking your browser"] = new("Bot protection", "Cloudflare"),
            ["<span data-translate=\"checking_browser\">Checking your browser before accessing</span>"] = new("Bot protection", "Cloudflare"),
            ["This website is using a security service to protect itself from online attacks."] = new("Access denied", "Cloudflare"),
            ["<title>Доступ ограничен</title>"] = new("Censorship", "Rostelecom"),
            ["document.getElementById('validate_form_submit').disabled=true"] = new("Captcha", "Mail.ru"),
            ["Verifying your browser, please wait...<br>DDoS Protection by</font> Blazingfast.io"] = new("Bot protection", "Blazingfast"),
            ["404</h1><p class=\"error-card__description\">Мы не нашли страницу"] = new("Resolving", "MegaFon 404 page"),
            ["Доступ к информационному ресурсу ограничен на основании Федерального закона"] = new("Censorship", "MGTS"),
            ["Incapsula incident ID"] = new("Bot protection", "Incapsula"),
            ["<title>Client Challenge</title>"] = new("Bot protection", "Anti-bot challenge"),
            ["<title>DDoS-Guard</title>"] = new("Bot protection", "DDoS-Guard"),
            ["Сайт заблокирован хостинг-провайдером"] = new("Site-specific", "Site is disabled (Beget)"),
            ["Generated by cloudfront (CloudFront)"] = new("Request blocked", "Cloudflare"),
            ["/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page"] = new("Just a moment: bot redirect challenge", "Cloudflare"),
        };

    /// <summary>Suggested user-facing solutions per error type.</summary>
    public static IReadOnlyDictionary<string, string> Solutions { get; } =
        new Dictionary<string, string>
        {
            ["Captcha"] = "Try to switch to another IP address or to use service cookies",
            ["Bot protection"] = "Try to switch to another IP address",
            ["Censorship"] = "Switch to another internet service provider",
            ["Request timeout"] = "Try to increase timeout or to switch to another internet service provider",
            ["Connecting failure"] = "Try to decrease number of parallel connections (e.g. -n 10)",
        };

    /// <summary>Reasons that hint at user action (e.g. login required → cookies).</summary>
    public static IReadOnlyDictionary<string, string> Reasons { get; } =
        new Dictionary<string, string>
        {
            ["Login required"] = "Add authorization cookies through `--cookies-jar-file` (see cookies.txt)",
        };

    /// <summary>Error types considered transient. Anything not in this set is permanent.</summary>
    public static IReadOnlySet<string> TemporaryTypes { get; } = new HashSet<string>
    {
        "Request timeout",
        "Unknown",
        "Request failed",
        "Connecting failure",
        "HTTP",
        "Proxy",
        "Interrupted",
        "Connection lost",
    };

    /// <summary>Percentage threshold above which an error type is considered "important".</summary>
    public const int Threshold = 3;

    /// <summary>Returns the first matching fingerprint in <paramref name="text"/>, or null.</summary>
    public static CheckError? Detect(string text)
    {
        if (string.IsNullOrEmpty(text))
        {
            return null;
        }

        foreach (var (flag, err) in Fingerprints)
        {
            if (text.Contains(flag, StringComparison.Ordinal))
            {
                return err;
            }
        }

        return null;
    }

    /// <summary>Returns the suggested solution for an error type, or empty string.</summary>
    public static string SolutionOf(string errorType) =>
        Solutions.TryGetValue(errorType, out var s) ? s : string.Empty;

    /// <summary>True when an error type is permanent (not transient).</summary>
    public static bool IsPermanent(string errorType) => !TemporaryTypes.Contains(errorType);

    /// <summary>
    /// Aggregates errors by type, ranks them by frequency, and rounds the percentage
    /// to two decimals. Mirrors <c>errors.extract_and_group</c>.
    /// </summary>
    public static IReadOnlyList<ErrorStat> ExtractAndGroup(IEnumerable<MaigretCheckResult> results)
    {
        ArgumentNullException.ThrowIfNull(results);

        var counts = new Dictionary<string, int>(StringComparer.Ordinal);
        var total = 0;
        foreach (var r in results)
        {
            total++;
            if (r.Error is null)
            {
                continue;
            }

            counts[r.Error.Type] = counts.GetValueOrDefault(r.Error.Type) + 1;
        }

        return total == 0
            ? []
            : [.. counts
            .OrderByDescending(p => p.Value)
            .Select(p => new ErrorStat(
                Type: p.Key,
                Count: p.Value,
                Percent: Math.Round(100.0 * p.Value / total, 2)))];
    }

    /// <summary>True when the error type is "important" enough to warn about.</summary>
    public static bool IsImportant(ErrorStat stat) => stat.Percent >= Threshold;

    /// <summary>
    /// Builds the user-facing notification list for noisy error types. Mirrors
    /// <c>errors.notify_about_errors</c>: pairs of (text, marker) suitable for printing.
    /// </summary>
    public static IReadOnlyList<(string Text, string Marker)> NotifyAboutErrors(
        IEnumerable<MaigretCheckResult> results,
        bool showStatistics = false)
    {
        var stats = ExtractAndGroup(results);
        var output = new List<(string Text, string Marker)>();

        var anyImportant = false;
        foreach (var s in stats)
        {
            if (!IsImportant(s))
            {
                continue;
            }

            var text = $"Too many errors of type \"{s.Type}\" ({s.Percent}%)";
            var solution = SolutionOf(s.Type);
            if (!string.IsNullOrEmpty(solution))
            {
                text = string.Concat(text, ". ", char.ToUpperInvariant(solution[0]) + solution[1..]);
            }

            output.Add((text, "!"));
            anyImportant = true;
        }

        if (showStatistics)
        {
            output.Add(("Verbose error statistics:", "-"));
            foreach (var s in stats)
            {
                output.Add(($"{s.Type}: {s.Percent}%", "!"));
            }
        }

        if (anyImportant)
        {
            output.Add(("You can see detailed site check errors with a flag `--print-errors`", "-"));
        }

        return output;
    }
}
